[project]
name = "Rec"
version = "0.1.0"
description = "I implement SASRec and BERT4Rec"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "ipdb>=0.13.13",
    "matplotlib>=3.10.7",
    "pandas>=2.3.3",
    "torch>=2.9.0",
    "tqdm>=4.67.1",
]
